name: Bot CI

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show files
        run: ls -la

      - name: Syntax check
        run: python -m py_compile bot.py

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy hook
        run: curl -X POST ${{ secrets.RENDER_HOOK || secrets.RAILWAY_HOOK }}
