name: Bot CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Show files
      run: ls -la

    - name: Check bot file
      run: python -m py_compile ./bot.py
